### ISSUE TITLE
Testing todo UI

### ISSUE THREAD

**Issue by laras126** [laras126/wceu-2018#1]
Lecture: An overview of how Gutenberg works

- [ ] View the block from the frontend and see where the styles are coming from using the Devtools Inspector (right click on the element, Inspect Element).
- [ ] Create a few blocks in Gutenberg (one of them should be a paragraph block). 
  - [ ] Adjust some settings for the paragraph block in the sidebar.
- [ ] Deactivate the Gutenberg plugin.
- [ ] Reload the WYSIWYG editor and make note of the comments surrounding blocks. 
- [ ] Reload the frontend and make note of any styling differences.
- [ ] Reactivate Gutenberg and see blocks re-appear.
